name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Install frontend dependencies
        working-directory: ./news-navigator-main
        run: npm install

      - name: Build frontend
        working-directory: ./news-navigator-main
        run: npm run build

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend with Maven
        working-directory: ./demo
        run: mvn clean install -DskipTests

      - name: Run backend tests
        working-directory: ./demo
        run: mvn test

      - name: Stop and remove containers
        run: docker compose -f docker-compose.yml down
